<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Fable.React" Version="7.4.3" />
    <PackageVersion Include="FSharp.Core" Version="10.1.203" />
    <PackageVersion Include="FSharp.SystemTextJson" Version="1.4.36" />
    <PackageVersion Include="StreamJsonRpc" Version="2.25.29" />
    <PackageVersion Include="Fable.Compiler" Version="5.15.0" />
    <PackageVersion Include="Suave" Version="2.6.2" />
    <PackageVersion Include="protobuf-net" Version="3.2.30" />
    <!-- lock transitive dependencies -->
    <PackageVersion Include="Fable.AST" Version="5.0.0" />
    <PackageVersion Include="System.Collections" Version="4.3.0" />
    <PackageVersion Include="System.Diagnostics.Debug" Version="4.3.0" />
    <PackageVersion Include="System.IO.FileSystem.Primitives" Version="4.3.0" />
    <PackageVersion Include="System.Runtime.Extensions" Version="4.3.1" />
    <PackageVersion Include="MessagePack" Version="2.5.302" />
    <!-- unit test project -->
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageVersion Include="Nerdbank.Streams" Version="2.13.31" />
    <PackageVersion Include="NUnit" Version="4.3.2" />
    <PackageVersion Include="NUnit3TestAdapter" Version="5.0.0" />
  </ItemGroup>
</Project>