name: PR

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4

      - name: Restore tools
        run: dotnet tool restore

      - name: Restore solution
        run: dotnet restore

      - name: Install node_modules
        run: bun install --frozen-lockfile

      - name: TypeScript check
        run: bun run lint

      - name: Build daemon
        run : bun run postinstall

      - name: Build sample
        run: bun i && bun run build 2>&1 | grep -i "error" && exit 1 || true
        working-directory: ./sample-project

      - name: Build docs
        run: dotnet fsdocs build --noapidocs --projects "$(pwd)/Fable.Daemon/Fable.Daemon.fsproj"

      - name: Generate tgz package
        run: npm pack

      - name: Cache package
        uses: actions/cache@v3
        with:
          path: |
            *.tgz
          key: ${{ runner.os }}-package-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-package-

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Retrieve cached package
        uses: actions/cache@v3
        with:
          path: |
            *.tgz
          key: ${{ runner.os }}-package-${{ github.sha }}

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          BRANCH_NAME=$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} | tr / -)
          COMMIT_HASH=${GITHUB_SHA::8}
          TAG_NAME="pr-${BRANCH_NAME}-${COMMIT_HASH}"
          npm publish $(ls *.tgz) --tag ${TAG_NAME}